version: '3.9'


services:
  app:
    build: .
    ports:
      - "3000:3000"
    # depends_on:
    #   db:
    #     condition: service_started
    #   redis:
    #     condition: service_started
    environment:
      # DATABASE_URL: postgres://postgres:admin@db:5432/sdoh_coordination_platform_client_production
      # REDIS_URL: redis://redis:6379/0
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      # APPLICATION_HOST: "localhost:3000"
    restart: unless-stopped
    command: >
      bash -c "bundle exec rails server -p 3000"

  # redis:
  #   image: redis:alpine
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data:/data

  # db:
  #   image: postgres:alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_DB: sdoh_coordination_platform_client_production
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
#   redis_data:
